spring:
  application:
    name: spring-ai-quickstart
  ai:
    chat:
      client:
        enabled: false
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-8932ad48263c4b89950145445e068d3c
      chat:
        options:
          model: qwen3.5-plus

server:
  port: 9001